version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  telemetry:
    image: iqtlabs/edgetech-telemetry:latest
    build:
      context: ./telemetry
      dockerfile: ./Dockerfile
    volumes:
      - /sys/class/power_supply/rk818-battery/capacity:/battery_capacity
      - /proc/uptime:/uptime
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on: 
      - mqtt
    env_file:
      - .env