version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  telemetry:
    image: iqtlabs/edgetech-telemetry:latest
    network_mode: "host"
    build:
      context: ../edgetech-telemetry-pinephone/telemetry
      dockerfile: ./Dockerfile
    environment:
      - C2_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
      - TELEMETRY_TOPIC=/AISonobuoy/<HOSTNAME>/telemetry/telemetry/string
      - DATA_ROOT=/sensor-data
      - MQTT_IP=localhost
    volumes:
      - ./sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt