version: "3"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  telemetry:
    image: telemetryimage
    restart: always
    network_mode: "host"
    depends_on: 
      - mqtt-broker
    volumes:
      - type: bind
        source: ./config
        target: /root/config
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        BASE_MQTT_PUBLISH_TOPIC: '/telemetry/pub'
        BASE_MQTT_SUBSCRIBE_TOPIC: '/telemetry/sub'