version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  telemetry:
    image: iqtlabs/edgetech-telemetry-pinephone:latest
    #restart: always
    network_mode: "host"
    depends_on: 
      - mqtt
    build:
      context: ./telemetry-pinephone
      dockerfile: ./Dockerfile
      args:
        BASE_MQTT_PUBLISH_TOPIC: '/telemetry/pub'
        BASE_MQTT_SUBSCRIBE_TOPIC: '/telemetry/sub'
    volumes:
      - './data:/root/data'  