version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    restart: unless-stopped
  telemetry:
    image: iqtlabs/edgetech-telemetry:latest
    build:
      context: ./telemetry
      dockerfile: ./Dockerfile
    volumes:
      # Note that these volumes are for demonstration purposes only, although most 
      # of the information required can be found in similar locations on most Linux flavors. 
      - /sys/class/power_supply/rk818-battery/capacity:/battery_capacity
      - /proc/uptime:/uptime
      - /proc/meminfo:/meminfo
      - /sys/class/thermal/thermal_zone0/temp:/cpu_temp
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on: 
      - mqtt
    env_file:
      - .env